# Default MobHealth Config file
# 
# disableSpout: [true|false] - force messages to display in chat even if spout is present.
# disableChat: [true|false] - force messages to display only if spout is present.
# setting both these to true will cause no notifications to appear!  
#
# showRPG: [true|false] - show RPG style notification (requires SpoutCraft).
#
# showSideNotification: [true|false] - show side style notification (requires SpoutCraft).
#
# usePermissions: [true|false] - true requires MobHealth.show (or MobHealth.*) to show message to player.
#
# disablePlayers: [true|false] - disable notifications for player hits.
# disableMonsters: [true|false] - disable notifications for 'monster' hits.
# disableAnimals: [true|false] - disable notifications for 'animal' hits.
# disablePets: [true|false] - disable notifications for hits from tamed mobs.
#
# damageDisplayType: [1|2|3|4]
#    1: display damage inflicted.  
#    2: display damage taken.
#    3: display damage inflicted (-amount resisted)
#    4: display damage taken (+amount resisted)
# hideNoDammage: [true|false] Hide notifications that inflict 0 damage.  Custom Egg and Snowball notifications are exempt.
# debugMode: [true|false] Enable extra debugging messages in server logs.

disableSpout: false
disableChat: false

showRPG: false
showSideNotification: false

healthBarSize: 10
showPlayerHeadHealth: true
showMobHeadHealth: true
usePercentForPlayer: true
useBarForMobs: true
cleanDeathMessages: true

hideBarForAnimal: false
hideBarForVillager: true
hideBarForNPC: true
forceBarHide: [EnderDragon,Wither]
showbarCustomNameOnly: false
alwaysVisable: false

usePermissions: false

disablePlayers: false
disableMonsters: false
disableAnimals: false
disablePets: false

damageDisplayType: 4

hideNoDammage: true

defaultToggle: true

updateCheck: true
doUpdate: true
debugMode: false

useActionBar: true
